# Agent Hook: New Adapter Generator
# Automates the creation of boilerplate for new protocol adapters

hook:
  name: "new-adapter"
  description: "Generate boilerplate files for a new protocol adapter"
  version: "1.0.0"
  trigger: "command"

command:
  name: "new-adapter"
  usage: "kiro new-adapter --source [PROTOCOL] --target [PROTOCOL]"
  
  parameters:
    - name: "source"
      type: "string"
      required: true
      description: "Source protocol (REST, GraphQL, gRPC, SOAP, WebSocket)"
      validation: "Must be one of the 5 supported protocols"
    
    - name: "target"
      type: "string"
      required: true
      description: "Target protocol (REST, GraphQL, gRPC, SOAP, WebSocket)"
      validation: "Must be one of the 5 supported protocols"
  
  examples:
    - "kiro new-adapter --source REST --target GraphQL"
    - "kiro new-adapter --source gRPC --target WebSocket"

actions:
  - name: "Create Kiro Spec"
    description: "Generate a spec file for the adapter"
    output: ".kiro/specs/{{source}}-to-{{target}}-adapter.yaml"
    template: |
      # {{source}} to {{target}} Adapter Specification
      # Auto-generated by new-adapter hook
      
      adapter:
        name: "{{source}} to {{target}} Adapter"
        source_protocol: "{{source}}"
        target_protocol: "{{target}}"
        version: "1.0.0"
      
      purpose: |
        Generate a Node.js adapter that accepts {{source}} requests
        and transforms them into {{target}} format.
      
      # TODO: Fill in the rest of the spec based on protocols
      # Refer to rest-adapter.yaml or graphql-adapter.yaml for structure
  
  - name: "Create Template File"
    description: "Generate a placeholder template"
    output: "backend/src/templates/{{source}}-to-{{target}}.js"
    template: |
      /**
       * {{source}} to {{target}} Adapter
       * Auto-generated by new-adapter hook
       * 
       * TODO: Implement the adapter logic
       * Use Kiro vibe coding to generate the full implementation
       */
      
      async function {{source}}To{{target}}Adapter(payload, config) {
        try {
          // TODO: Implement transformation logic
          console.log('{{source}} payload:', payload);
          console.log('Target {{target}} config:', config);
          
          throw new Error('Not yet implemented - use Kiro to generate!');
        } catch (error) {
          return {
            success: false,
            error: error.message
          };
        }
      }
      
      module.exports = { {{source}}To{{target}}Adapter };
  
  - name: "Update Adapter Service"
    description: "Add template reference to AdapterService"
    instructions: |
      Manually update backend/src/services/AdapterService.ts:
      
      1. Add condition in generateAdapterCode():
```typescript
         else if (sourceProtocol === '{{source}}' && targetProtocol === '{{target}}') {
           templatePath = path.join(__dirname, '../templates/{{source}}-to-{{target}}.js');
         }
```
      
      2. Test that the template loads correctly
  
  - name: "Create Test File"
    description: "Generate a test template"
    output: "backend/tests/adapters/{{source}}-to-{{target}}.test.ts"
    template: |
      import { describe, it, expect } from 'vitest';
      // import { {{source}}To{{target}}Adapter } from '../../src/templates/{{source}}-to-{{target}}';
      
      describe('{{source}} to {{target}} Adapter', () => {
        it.todo('should transform {{source}} payload to {{target}} format');
        it.todo('should handle errors gracefully');
        it.todo('should validate input payload');
      });

automation:
  workflow: |
    When this hook is triggered:
    
    1. Parse command-line arguments (--source, --target)
    2. Validate protocols are supported
    3. Check if adapter already exists (prevent overwrite)
    4. Generate spec file from template
    5. Generate code template file
    6. Generate test file
    7. Print success message with next steps
    8. Open generated spec file in Kiro for editing

next_steps:
  message: |
    ✅ Adapter boilerplate created!
    
    Next steps:
    1. Edit .kiro/specs/{{source}}-to-{{target}}-adapter.yaml
    2. Fill in the spec with protocol details
    3. Use Kiro vibe coding to generate the full adapter:
       "Generate {{source}} to {{target}} adapter based on spec"
    4. Test the adapter with sample data
    5. Update AdapterService.ts to use the new template

integration_with_kiro:
  description: |
    This hook demonstrates Kiro's automation capabilities.
    It reduces the manual work of creating new adapters from
    30 minutes to 30 seconds.
  
  future_enhancements:
    - "Auto-detect protocol structure from example payloads"
    - "Generate field mappings automatically"
    - "Create integration tests with mock data"
    - "Deploy adapter to production environment"