'use client';

import { useState } from 'react';
import { motion } from 'framer-motion';
import { KiroBadge } from '../ui/KiroBadge';

interface CodeViewerProps {
  code: string;
  language?: string;
  filename?: string;
}

export function CodeViewer({ code, language = 'javascript', filename = 'adapter.js' }: CodeViewerProps) {
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([code], { type: 'text/javascript' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  };

  const lineCount = code.split('\n').length;

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="w-full max-w-5xl mx-auto mt-12 p-6 bg-[#0d1f16] border-2 border-[#39ff14] rounded-2xl"
    >
      {/* Header */}
      <div className="flex items-center justify-between mb-4">
        <div>
          <h3 className="text-2xl font-bold text-[#39ff14]">
            Generated Adapter Code ⚡
          </h3>
          <p className="text-gray-400 text-sm mt-1">
            {lineCount} lines • {language}
          </p>
        </div>
        
        <div className="flex gap-3">
          {/* Copy button */}
          <motion.button
            onClick={handleCopy}
            whileHover={{ scale: 1.05 }}
            whileTap={{ scale: 0.95 }}
            className={`
              px-4 py-2 rounded-lg font-semibold transition-colors
              ${copied 
                ? 'bg-green-900 text-green-300 border border-green-500' 
                : 'bg-gray-800 text-gray-300 border border-gray-600 hover:border-[#39ff14]'
              }
            `}
          >
            {copied ? '✓ Copied!' : '📋 Copy'}
          </motion.button>
          
          {/* Download button */}
          <motion.button
            onClick={handleDownload}
            whileHover={{ scale: 1.05 }}
            whileTap={{ scale: 0.95 }}
            className="px-4 py-2 bg-[#39ff14] text-black font-semibold rounded-lg hover:shadow-[0_0_20px_rgba(57,255,20,0.6)]"
          >
            💾 Download
          </motion.button>
        </div>
      </div>

      {/* Code display */}
      <div className="relative">
        <div className="overflow-auto max-h-[600px] bg-gray-900 rounded-lg">
          <div className="flex">
            {/* Line numbers */}
            <div className="py-4 px-3 bg-gray-950 text-gray-500 text-right select-none font-mono text-sm">
              {Array.from({ length: lineCount }, (_, i) => (
                <div key={i + 1}>{i + 1}</div>
              ))}
            </div>
            
            {/* Code */}
            <pre className="flex-1 py-4 px-4 text-sm overflow-x-auto">
              <code className="text-gray-100 font-mono whitespace-pre">
                {code}
              </code>
            </pre>
          </div>
        </div>
      </div>

      {/* Footer info */}
      {/* Footer info */}
      <div className="mt-4 p-4 bg-gray-900/50 rounded-lg border border-gray-700 flex items-center justify-between">
        <p className="text-sm text-gray-400">
          💡 <strong className="text-[#39ff14]">Generated by Kiro</strong> based on your configuration. 
          This code is production-ready and can be downloaded or integrated into your project.
        </p>
        <KiroBadge variant="large" />
      </div>
    </motion.div>
  );
}