import type { AdapterConfig, Adapter } from './types/adapter';

const API_URL = 'https://frankenstack.onrender.com/api';

export async function fetchBackendHealth() {
  const response = await fetch(`${API_URL}/health`);
  const data = await response.json();
  return data;
}

export async function createAdapter(config: AdapterConfig): Promise<Adapter> {
  const response = await fetch(`${API_URL}/adapters`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      sourceProtocol: config.sourceProtocol,
      targetProtocol: config.targetProtocol,
      code: '// Adapter code will be generated by Kiro\nfunction placeholder() {}',
      config: config,
    }),
  });

  if (!response.ok) {
    throw new Error('Failed to create adapter');
  }

  const data = await response.json();
  return data.adapter;
}

export async function listAdapters(): Promise<Adapter[]> {
  const response = await fetch(`${API_URL}/adapters`);
  
  if (!response.ok) {
    throw new Error('Failed to fetch adapters');
  }

  const data = await response.json();
  return data.adapters;
}